name = "image-to-text"
main = "src/index.js" # or src/worker.js
compatibility_date = "2024-06-17" # Use today's date or a later one

[[ai_models]]
binding = "AI" # This makes env.AI available in your Worker

# Add this section
[vars]
ACCOUNT_ID = "30d911bbabfa0db53eedb9cd5fecb31d" # Replace with your actual Cloudflare Account ID
API_TOKEN = "HvlYoy8n6LbdMuIiEmAnNmhHVz_lnS4tt2ek_IDz"
